const T=window.THREE,$=s=>document.querySelector(s), VERSION='workshop-20260918-v1';
window.lucide.createIcons();
const box=$('#scene'),caption=$('#caption'),config={big:false,sails:1,apples:3,color:'#dc7463',route:'meadow'};
const numPy=['líng','yī','èr','sān','sì','wǔ'], words=['零','一','二','三','四','五'];
const ruby=(s,p)=>`<ruby>${s}<rt>${p}</rt></ruby>`;
const key='luoyi-workshop-exploration-v1';let stored;try{stored=JSON.parse(localStorage.getItem(key)||'{}')}catch{stored={}}
const record={version:VERSION,sessions:Number(stored?.sessions)||0,events:Array.isArray(stored?.events)?stored.events.slice(-150):[]};record.sessions++;
function persist(){try{localStorage.setItem(key,JSON.stringify(record))}catch{}}
function note(kind,extra={}){record.events.push({time:new Date().toISOString(),kind,...extra});record.events=record.events.slice(-200);persist()}note('open');
let phase='build',muted=false,audio,act=null,view='driver',time=0,last=performance.now(),toastUntil=0,shown=0,pause=false,lastOutcome='',lastTravel=0;
function speak(id){if(muted)return;if(audio){audio.pause();audio.currentTime=0}audio=new Audio(`audio/${id}.mp3`);audio.play().catch(()=>{});}
function say(text,id){caption.textContent=text;if(id)speak(id)}
let audioContext;
function ping(high=false){if(muted)return;try{audioContext||=new (window.AudioContext||window.webkitAudioContext)();audioContext.resume();const o=audioContext.createOscillator(),g=audioContext.createGain();o.type='sine';o.frequency.setValueAtTime(high?660:440,audioContext.currentTime);o.frequency.exponentialRampToValueAtTime(high?990:550,audioContext.currentTime+.12);g.gain.setValueAtTime(.055,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.18);o.connect(g).connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+.2)}catch{}}
$('#sound').onclick=()=>{muted=!muted;$('#sound').innerHTML=`<i data-lucide="volume-${muted?'x':'2'}"></i>`;$('#sound').setAttribute('aria-label',muted?'打开声音':'关闭声音');window.lucide.createIcons();if(muted)audio?.pause();else speak(phase==='build'?'intro':phase==='drive'?(config.route==='gate'?'gate':'wind'):lastOutcome==='arrive'?'arrive':'again')};
function toast(html){$('#toast').innerHTML=html;$('#toast').classList.add('show');toastUntil=time+2.4}
let renderer;
try{renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});}catch{ $('#loading').textContent='这个浏览器暂时无法打开三维画面。请用 Safari 或 Chrome 重新打开。';throw Error('WebGL unavailable'); }
renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.6));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputEncoding=T.sRGBEncoding;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;box.prepend(renderer.domElement);
const scene=new T.Scene();scene.background=new T.Color('#bfe0dd');scene.fog=new T.Fog('#bfe0dd',22,65);
const camera=new T.PerspectiveCamera(43,1,.1,100);const target=new T.Vector3(),camGoal=new T.Vector3(),lookGoal=new T.Vector3();
scene.add(new T.HemisphereLight('#fff8df','#6d9b90',1.25));const sunlight=new T.DirectionalLight('#fff0d0',2.15);sunlight.position.set(-7,13,7);sunlight.castShadow=true;sunlight.shadow.mapSize.set(1024,1024);sunlight.shadow.camera.left=-10;sunlight.shadow.camera.right=10;sunlight.shadow.camera.top=10;sunlight.shadow.camera.bottom=-30;sunlight.shadow.normalBias=.035;scene.add(sunlight);scene.add(sunlight.target);
const mats=new Map();function mat(color){if(!mats.has(color))mats.set(color,new T.MeshStandardMaterial({color,roughness:.67}));return mats.get(color)}
function mesh(geo,c,p,x=0,y=0,z=0){const o=new T.Mesh(geo,typeof c==='string'?mat(c):c);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;p.add(o);return o}
function cube(p,w,h,d,c,x=0,y=0,z=0){return mesh(new T.BoxGeometry(w,h,d),c,p,x,y,z)}
function ball(p,r,c,x=0,y=0,z=0,sx=1,sy=1,sz=1){const o=mesh(new T.SphereGeometry(r,20,14),c,p,x,y,z);o.scale.set(sx,sy,sz);return o}
function rod(p,r,h,c,x=0,y=0,z=0){return mesh(new T.CylinderGeometry(r,r,h,16),c,p,x,y,z)}
function limb(p,a,b,r,c){const d=new T.Vector3().subVectors(b,a),o=rod(p,r,d.length(),c);o.position.copy(a).add(b).multiplyScalar(.5);o.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),d.normalize());return o}
const v=(x,y,z)=>new T.Vector3(x,y,z);
const ground=cube(scene,90,.3,100,'#87b79b',0,-.22,-18);const pond=mesh(new T.CircleGeometry(8,64),'#6ebeb8',scene,-9,-.04,-10);pond.rotation.x=-Math.PI/2;
for(let i=0;i<12;i++){const leaf=mesh(new T.CircleGeometry(.24+(i%3)*.07,24,.15,Math.PI*1.85),'#4b9e83',scene,-5-(i%4)*1.3,-.015,-7-Math.floor(i/4)*1.9);leaf.rotation.x=-Math.PI/2;if(i%3===0)ball(scene,.14,'#f1b5b6',leaf.position.x,.08,leaf.position.z,1,.5,1)}
const scenery=new T.Group();scene.add(scenery);const road=new T.Group();scene.add(road);
function groundHeight(z){const d=-z;if(config.route!=='meadow')return 0;if(d>=6&&d<11)return (d-6)*.14;if(d>=11&&d<16)return .7-(d-11)*.14;return 0}
function buildRoad(){road.traverse(o=>{if(o.isMesh)o.geometry.dispose()});road.clear();for(let i=0;i<27;i++){const z=2-i,y1=groundHeight(z+.5)+.025,y2=groundHeight(z-.5)+.025;const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute([-2,y1,z+.5,2,y1,z+.5,-2,y2,z-.5,2,y1,z+.5,2,y2,z-.5,-2,y2,z-.5],3));g.computeVertexNormals();mesh(g,'#e3ce9f',road);for(const x of[-2.05,2.05])ball(road,.12,'#f3e5bb',x,groundHeight(z),z,1,.55,1)}
 arch.visible=config.route==='gate';windmill.visible=config.route==='meadow';}
function tree(x,z,size,c){const g=new T.Group();g.position.set(x,0,z);g.scale.setScalar(size);scenery.add(g);rod(g,.16,1.8,'#9f7154',0,.9);const branch=rod(g,.095,1,'#9f7154',.23,1.2);branch.rotation.z=-.7;ball(g,.85,c,0,2.05,0,1.15,1.1,1);ball(g,.63,c,-.5,1.7,.12);ball(g,.55,c,.5,1.82,.1);ball(g,.5,'#93bd7d',-.25,2.58,-.04)}
for(let i=0;i<15;i++){tree((i%2?-1:1)*(3.6+i%3),-3-i*1.75,.8+(i%4)*.1,['#679e7e','#548f76','#72a17e'][i%3])}
function flower(x,z){const g=new T.Group();g.position.set(x,.14,z);scenery.add(g);for(let j=0;j<5;j++)ball(g,.085,'#edb4ac',Math.cos(j*1.257)*.13,0,Math.sin(j*1.257)*.13,1,.45,1);ball(g,.07,'#f2d46d',0,.01,0)}for(let i=0;i<25;i++)flower((i%2?1:-1)*(2.7+i%4*.4),2-i*1.1);
const arch=new T.Group();arch.position.z=-9;scene.add(arch);cube(arch,.6,2.7,.8,'#9d7458',-1.85,1.25);cube(arch,.6,2.7,.8,'#9d7458',1.85,1.25);cube(arch,4.3,.65,1.1,'#9d7458',0,2.63);for(let i=0;i<5;i++)ball(arch,.62,'#6b9a68',-1.8+i*.9,3.03,-.02,1,.55,.9);const gateSign=cube(arch,.75,.3,.1,'#ecd9a9',1.82,1.25,.45);
cube(arch,3.3,.07,1.13,'#efc677',0,2.33);
const windmill=new T.Group();windmill.position.set(3.5,0,-11);scene.add(windmill);mesh(new T.CylinderGeometry(.55,.85,3,16),'#eadfc0',windmill,0,1.5);mesh(new T.ConeGeometry(.83,.95,16),'#b87660',windmill,0,3.4);const blades=new T.Group();blades.position.set(0,2.8,.63);windmill.add(blades);for(let i=0;i<4;i++){const wing=cube(blades,.18,2.6,.12,'#f4e9bf');wing.rotation.z=i*Math.PI/2;const sail=cube(wing,.42,.75,.06,'#efd397',.2,1,.05)}ball(blades,.18,'#956e52',0,0,.1);
const picnic=new T.Group();picnic.position.set(0,0,-23);scene.add(picnic);cube(picnic,3.6,.035,2.7,'#d88b72',0,.01);for(let i=0;i<4;i++)for(let j=0;j<3;j++)cube(picnic,.45,.01,.45,'#f8dab7',-1.4+i*.85,.035,-.9+j*.85);const bowl=mesh(new T.CylinderGeometry(.55,.4,.2,24),'#e6c78e',picnic,0,.14);const delivery=new T.Group();picnic.add(delivery);
const car=new T.Group();scene.add(car);const carPaint=new T.MeshStandardMaterial({color:config.color,roughness:.55});const frame=new T.Group();car.add(frame);let wheels=[],flags=[],cargo=[];let nose;
function apple(p,x,y,z){const a=new T.Group();a.position.set(x,y,z);p.add(a);ball(a,.165,'#c95945',-.055,0,0,1,.9,1);ball(a,.165,'#dc7051',.055,0,0,1,.9,1);const stem=rod(a,.025,.13,'#785b3d',0,.17);stem.rotation.z=-.18;ball(a,.09,'#4c8866',.07,.2,0,1,.28,.6);return a}
function squirrel(p){const g=new T.Group();p.add(g);ball(g,.38,'#be7d53',0,.58,0,1,1.2,.85);ball(g,.3,'#ecd2a5',0,.6,.19,.78,1,.6);ball(g,.4,'#c1865c',0,1.18,.02,1,1,.88);for(const x of[-.25,.25]){ball(g,.15,'#ab6d4b',x,1.53,.04,.75,1.3,.65);ball(g,.095,'#d9a384',x,1.54,.135,.8,1.2,.35);ball(g,.12,'#f5ddaf',x*.65,1.04,.34,1.2,.9,.6);ball(g,.075,'#302b2a',x*.64,1.27,.343,.8,1,.5);ball(g,.021,'#fff8db',x*.64-.014,1.29,.38);ball(g,.11,'#b87950',x,.23,.19,1.1,.55,1.55)}ball(g,.07,'#6d493c',0,1.09,.46,1,.65,.6);const mouth=ball(g,.06,'#693f32',0,.994,.408,1,.35,.3);const tail=ball(g,.46,'#a96e4e',-.37,.57,-.34,.8,1.7,.6);tail.rotation.z=-.3;ball(g,.32,'#be8255',-.53,1.06,-.38);const scarf=cube(g,.62,.12,.36,'#68a99a',0,.89,.1);const arm=new T.Group();arm.position.set(.32,.75,0);g.add(arm);ball(arm,.09,'#bf8054',.05,-.15,.04,1,2,1);g.userData={mouth,arm,tail};return g}
const ali=squirrel(scene);ali.position.set(-1.7,0,.05);ali.rotation.y=.35;const friend=squirrel(picnic);friend.position.set(1.2,0,-.5);friend.rotation.y=-.3;friend.scale.setScalar(.9);
function buildCar(){const old=[];frame.traverse(o=>{if(o.isMesh)old.push(o.geometry)});frame.clear();old.forEach(g=>g.dispose());wheels=[];flags=[];cargo=[];const r=config.big?.56:.34,base=r+.22;car.userData={radius:r,top:base+(config.sails? .8+config.sails*.37:.85)};cube(frame,1.8,.35,2.45,carPaint,0,base,0);cube(frame,1.57,.14,2.1,'#edc990',0,base+.23,0);for(const z of[-.75,.75]){const axle=rod(frame,.055,2.2,'#52635c',0,r,z);axle.rotation.z=Math.PI/2;for(const x of[-1.04,1.04]){const w=new T.Group();w.position.set(x,r,z);frame.add(w);const tire=rod(w,r,.2,'#47675d');tire.rotation.z=Math.PI/2;const rim=rod(w,r*.73,.213,'#eadbb8');rim.rotation.z=Math.PI/2;const hub=rod(w,r*.2,.23,'#b98b55');hub.rotation.z=Math.PI/2;for(let k=0;k<5;k++){const spoke=cube(w,.22,.05,r*1.38,'#ad926b');spoke.rotation.x=k*Math.PI/5}wheels.push(w)}}
cube(frame,1.4,.18,.32,'#376d62',0,base+.49,.57);const bumper=cube(frame,1.9,.16,.22,'#e7be74',0,base,-1.3);for(const x of[-.54,.54])ball(frame,.16,'#fff0ad',x,base+.19,-1.28,1,1,.55);ball(frame,.17,'#4c796b',0,base+.47,-.92,1,.5,1);cube(frame,.06,.2,.06,'#628474',0,base+.57,-.94);
for(const x of[-.4,.4]){cube(frame,.7,.08,.95,'#b98850',x,base+.36,-.32);for(let j=0;j<3;j++){cube(frame,.045,.24,.92,'#c29b67',x-.31+j*.31,base+.51,-.32)}for(const z of[-.77,.14])cube(frame,.72,.24,.045,'#c29b67',x,base+.5,z)}
for(let i=0;i<config.apples;i++){const side=i<2?-.4:.4,j=i<2?i:i-2;cargo.push(apple(frame,side,base+.64,-.64+j*.28))}
if(config.sails){const mastH=.55+config.sails*.37;rod(frame,.038,mastH,'#927750',0,base+.25+mastH/2,.91);for(let i=0;i<config.sails;i++){const f=new T.Group();f.position.set(0,base+.69+i*.37,.91);frame.add(f);const cloth=new T.PlaneGeometry(1.2,.34,12,4),pos=cloth.attributes.position;for(let k=0;k<pos.count;k++){const x=pos.getX(k),y=pos.getY(k);pos.setZ(k,-.2*Math.cos(x/1.2*Math.PI)*Math.cos(y/.34*Math.PI))}cloth.computeVertexNormals();const m=mat(['#efd49b','#8bbda4','#dd9985'][i]);m.side=T.DoubleSide;mesh(cloth,m,f);cube(f,1.23,.035,.035,'#a68b59',0,.175);cube(f,1.23,.028,.035,'#a68b59',0,-.175);flags.push(f)}}
const bonnet=cube(frame,.7,.2,.35,'#366b60',0,base+.35,.95);ball(frame,.18,'#c7a975',0,base+.45,1.02);$('#wheelLabel').textContent=config.big?'大轮子':'小轮子';$('#wheels small').textContent=config.big?'点一下换小轮':'点一下换大轮';$('#sailNum').textContent=config.sails;$('#appleNum').textContent=config.apples;$('#apples small').textContent=config.apples===5?'装满啦，点一下拿空':'点一下装一颗';}
buildRoad();buildCar();
const breeze=new T.Group();scene.add(breeze);for(let i=0;i<20;i++){const petal=ball(breeze,.045,['#f6deba','#f9eacb','#a5c6a9'][i%3],(i%5-2)*1.4,1+(i%3)*.5,-i,1.8,.4,.7);petal.userData.startZ=-i}
let butterfly=new T.Group();scene.add(butterfly);const wings=[];for(const side of[-1,1]){const wing=ball(butterfly,.22,'#efd19f',side*.15,0,0,1.2,.12,1.6);wings.push(wing)}rod(butterfly,.03,.35,'#896d4e').rotation.x=Math.PI/2;
function change(type){if(phase!=='build')return;if(type==='wheels')config.big=!config.big;if(type==='sails')config.sails=(config.sails+1)%4;if(type==='apples')config.apples=(config.apples+1)%6;buildCar();note('change',{part:type,config:{...config}});ping();if(type==='apples')toast(`${ruby(words[config.apples],numPy[config.apples])} ${ruby('颗苹果','kē píng guǒ')}`);else toast(type==='wheels'?ruby(config.big?'大轮子':'小轮子',config.big?'dà lún zi':'xiǎo lún zi'):ruby(`${words[config.sails]}片帆`,`${numPy[config.sails]} piàn fān`));}
for(const id of['wheels','sails','apples'])$('#'+id).onclick=()=>change(id);
for(const id of['meadow','gate'])$('#'+id).onclick=()=>{if(phase!=='build')return;config.route=id;$('#meadow').classList.toggle('active',id==='meadow');$('#gate').classList.toggle('active',id==='gate');buildRoad();note('route',{route:id});say(id==='gate'?'树洞的门有点矮，你的小车会怎样？':'去风车坡野餐！试试你的车能不能爬上去。');ping();};
document.querySelectorAll('[data-paint]').forEach(b=>b.onclick=()=>{if(phase!=='build')return;config.color=b.dataset.paint;carPaint.color.set(config.color);document.querySelectorAll('[data-paint]').forEach(x=>x.classList.toggle('active',x===b));note('paint',{color:config.color});ping()});
function departure(){if(phase!=='build')return;phase='drive';view='driver';act={distance:0,speed:0,elapsed:0,stalled:0,bumped:false};delivery.clear();$('#buildTools').hidden=true;$('#go').hidden=true;$('#home').hidden=false;$('#result').hidden=true;$('#view').hidden=false;$('#view').textContent='看小车';$('#distance').hidden=false;box.classList.add('running');ali.visible=false;say(config.route==='gate'?'阿栗：出发！前面有个树洞。':'阿栗：出发！风车在前面转呢。',config.route==='gate'?'gate':'wind');note('run',{config:{...config}});ping(true)}
function finish(outcome){if(phase!=='drive')return;phase='result';lastOutcome=outcome;lastTravel=act.distance;$('#result').hidden=false;$('#view').hidden=true;$('#distance').hidden=true;$('#resultTitle').textContent=outcome==='arrive'?'珞伊的小车到啦！':outcome==='bump'?'车顶碰到小门啦':'小车在坡上歇脚啦';$('#resultText').textContent=outcome==='arrive'?(config.apples?'阿栗收到你带来的苹果。想换一条路，还是换一种小车？':'空车也跑到啦！阿栗在野餐垫上等你。下回想带什么？'):outcome==='bump'?'门没有变高。你想怎样让车顶低一点？':'这次风推着车，车却爬不动了。回去改一个零件，再看看。';const left=Math.min(2,config.apples),right=Math.max(0,config.apples-2);$('#learning').innerHTML=outcome==='arrive'?(config.apples?`${ruby('一共','yí gòng')} ${ruby(words[config.apples],numPy[config.apples])} ${ruby('颗苹果','kē píng guǒ')} <small>（${left} + ${right} = ${config.apples}）</small>`:ruby('这次空车到达','zhè cì kōng chē dào dá')):'';say(outcome==='arrive'?'阿栗：珞伊，你的发明送我们到野餐地啦！':outcome==='bump'?'阿栗：哎哟！这里的门有点矮。':'阿栗：这一段坡，有点费劲呢。',outcome);note('result',{outcome,config:{...config},distance:Number(act.distance.toFixed(2))});shown=0;if(outcome==='arrive')ping(true)}
function home(){if(phase==='build')return;if(phase==='drive')note('return',{distance:Number(act.distance.toFixed(2)),config:{...config}});phase='build';act=null;car.position.set(0,0,0);car.rotation.set(0,0,0);ali.visible=true;cargo.forEach(a=>a.visible=true);$('#result').hidden=true;$('#buildTools').hidden=false;$('#go').hidden=false;$('#home').hidden=true;$('#view').hidden=true;$('#distance').hidden=true;box.classList.remove('running');audio?.pause();say('阿栗：想怎么改，都听你的！','again');}
$('#go').onclick=departure;$('#home').onclick=home;$('#view').onclick=()=>{view=view==='driver'?'follow':'driver';$('#view').textContent=view==='driver'?'看小车':'坐到车上';note('view',{view})};
function report(){pause=true;audio?.pause();const e=record.events,runs=e.filter(e=>e.kind==='run'),results=e.filter(e=>e.kind==='result');$('#stats').innerHTML=`打开 ${record.sessions} 次 · 最近记录中试跑 ${runs.length} 次<br>更换零件 ${e.filter(e=>e.kind==='change').length} 次 · 到达 ${results.filter(e=>e.outcome==='arrive').length} 次<ul>${results.slice(-5).map(e=>`<li>${e.config.route==='gate'?'树洞':'坡道'}｜${e.config.big?'大':'小'}轮，${e.config.sails}片帆，${e.config.apples}颗苹果 → ${{arrive:'到达',bump:'碰到车顶',stuck:'坡上停住'}[e.outcome]}</li>`).join('')}</ul>`;$('#report').showModal()}
$('#parents').onclick=report;$('#closeReport').onclick=()=>$('#report').close();$('#report').addEventListener('close',()=>{pause=false;last=performance.now()});$('#export').onclick=()=>{const data={...record,scope:'本设备最近200个操作事件；不是学科能力评价，无录音与定位'};const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='珞伊的工坊探索记录.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
document.addEventListener('visibilitychange',()=>{if(document.hidden){audio?.pause();persist()}last=performance.now()});
function resize(){renderer.setSize(box.clientWidth,box.clientHeight);camera.aspect=box.clientWidth/box.clientHeight;camera.updateProjectionMatrix()};new ResizeObserver(resize).observe(box);resize();
function step(dt){time+=dt;if(toastUntil<time)$('#toast').classList.remove('show');blades.rotation.z-=dt*.8;butterfly.position.set(-1.7+Math.sin(time*.7)*1.1,1.9+Math.sin(time)*.2,-1.5+Math.cos(time*.7));wings.forEach((w,i)=>w.rotation.z=Math.sin(time*18)*(i?1:-1)*.55);breeze.visible=phase==='drive'&&config.route==='meadow';breeze.children.forEach((p,i)=>{p.position.z=car.position.z+4-((time*4+i*1.3)%20);p.position.x=Math.sin(i)*2.3});flags.forEach((f,i)=>f.rotation.y=Math.sin(time*3+i)*.12);
 ali.userData.arm.rotation.z=.3+Math.sin(time*2)*.3;ali.userData.tail.rotation.z=-.25+Math.sin(time)*.08;const talking=audio&&!audio.paused;ali.userData.mouth.scale.y=talking?.5+Math.abs(Math.sin(time*17))*.8:.35;friend.userData.arm.rotation.z=phase==='result'?1+Math.sin(time*4)*.3:0;
 if(phase==='drive'){act.elapsed+=dt;const dist=act.distance,previousY=car.position.y,mass=1+config.apples*.28,grade=groundHeight(-dist-.05)-groundHeight(-dist),drive=(1.7+config.sails*.85)/mass,rolling=config.big?.22:.4;const acceleration=drive-rolling-act.speed*.3-grade/.05*9;act.speed=Math.max(0,Math.min(3.8,act.speed+acceleration*dt));act.distance+=act.speed*dt;car.position.z=-act.distance;car.position.y=groundHeight(car.position.z);car.rotation.x=-Math.atan(grade/.05);if(view==='driver'){camera.position.z-=act.distance-dist;target.z-=act.distance-dist;camera.position.y+=car.position.y-previousY;target.y+=car.position.y-previousY}wheels.forEach(w=>w.rotation.x-=act.speed*dt/car.userData.radius);$('#distance').textContent=act.distance<6?'去野餐地':act.distance<15?(config.route==='gate'?'树洞前方':'穿过风车坡'):'快看到野餐垫啦';if(config.route==='gate'&&act.distance>9.35&&car.userData.top>2.30){act.distance=9.35;car.position.z=-9.35;car.rotation.x=-.04;finish('bump')}else if(act.distance>=21.2){act.distance=21.2;finish('arrive')}else{if(act.speed<.04&&act.elapsed>2)act.stalled+=dt;else act.stalled=0;if(act.stalled>.9||act.elapsed>38)finish('stuck')}}
 if(phase==='result'&&lastOutcome==='arrive'){shown+=dt;const n=Math.min(config.apples,Math.floor(shown/.35));for(let i=delivery.children.length;i<n;i++){apple(delivery,(i%3-1)*.25,.45,Math.floor(i/3)*.3-.15);cargo[i].visible=false}car.rotation.x=0;}
 const aspect=camera.aspect;if(phase==='build'){camGoal.set(3.8,3.0,5.6);if(aspect<.7)camGoal.multiplyScalar(.78/aspect);lookGoal.set(0,.88,0)}else if(phase==='drive'&&view==='driver'){camGoal.set(.10,car.position.y+car.userData.radius+1.65,car.position.z+.2);lookGoal.set(0,car.position.y+1.0,car.position.z-8)}else{camGoal.set(4.1,car.position.y+3.5,car.position.z+5.6);lookGoal.set(0,car.position.y+1.1,car.position.z-.8);if(phase==='result'&&lastOutcome==='bump'){camGoal.set(5.8,3.6,car.position.z+4.7);lookGoal.set(0,1.4,-9)}if(phase==='result'&&lastOutcome==='arrive'){camGoal.set(4.5,3.6,-17.6);lookGoal.set(0,.9,-22)}}camera.position.lerp(camGoal,1-Math.exp(-dt*3));target.lerp(lookGoal,1-Math.exp(-dt*3));camera.lookAt(target);sunlight.position.z=car.position.z+7;sunlight.target.position.z=car.position.z;}
camera.position.set(3.8,3,5.6);target.set(0,.88,0);camera.lookAt(target);$('#loading').hidden=true;
function animate(now){requestAnimationFrame(animate);const dt=Math.min(.05,(now-last)/1000);last=now;if(document.hidden||pause)return;step(dt);renderer.render(scene,camera)}requestAnimationFrame(animate);
window.workshopInspect=()=>({version:VERSION,phase,config:{...config},muted,top:car.userData.top,travel:act?.distance||lastTravel,outcome:lastOutcome,events:record.events,sessions:record.sessions,canvas:{width:box.clientWidth,height:box.clientHeight},voice:{paused:audio?.paused,time:audio?.currentTime},car:car.position.toArray(),view,camera:camera.position.toArray()});
