(function(){
'use strict';
const $=id=>document.getElementById(id),C=window.LanguageContent,KEY='luoyi-kite-language-v1';let stored={};try{stored=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{}
if(!stored||typeof stored!=='object')stored={};const validIndex=Number.isInteger(stored.index)&&stored.index>=0&&stored.index<C.rounds.length;
const validDraft=d=>d&&C.rounds.some(r=>r.id===d.round)&&typeof d.id==='string'&&Array.isArray(d.attempts)&&d.attempts.every(a=>a&&C.cast.some(c=>c.id===a.person)&&typeof a.correct==='boolean')&&['hints','replays','undo'].every(k=>Number.isInteger(d[k])&&d[k]>=0);
const validRecord=d=>validDraft(d)||(d&&d.kind==='director'&&['speaker','listener','recipient'].every(k=>C.cast.some(c=>c.id===d[k]))&&['我','你'].includes(d.word));
let index=validIndex?stored.index:0,records=Array.isArray(stored.records)?stored.records.filter(validRecord).slice(-80):[],draft=validDraft(stored.draft)&&stored.draft.round===C.rounds[index].id?stored.draft:null;
let muted=!!stored.muted,phase='home',paused=false,world,buttons={},labels={},selected=null,mode='story',elapsed=0,last=performance.now(),transitionAt=0,started=false,roundDone=false;
let directorState={speaker:'xin',listener:'yang',word:'我'},directorRun=0,voiceKey='',purpose='',queue=[],voiceToken=0,audioTimer=0,captionAt=0,storageOK=true;
const audio=new Audio();audio.preload='auto';const who=id=>C.cast.find(c=>c.id===id),r=()=>C.rounds[index];
const ruby=w=>'<ruby>'+w+'<rt>'+C.pinyin[w]+'</rt></ruby>';
function textRuby(text){return text.replace(/[我你他]/g,w=>ruby(w))}
function save(){try{localStorage.setItem(KEY,JSON.stringify({version:1,index,records,draft,muted}));storageOK=true}catch{storageOK=false}$('storageWarning').hidden=storageOK}
function entry(){return {id:Date.now()+'-'+Math.random().toString(36).slice(2),round:r().id,title:r().title,word:r().word,attempts:[],hints:0,replays:0,undo:0,complete:false}}
function stopVoice(){voiceToken++;clearTimeout(audioTimer);captionAt=0;audio.pause();audio.removeAttribute('src');audio.load();queue=[];purpose='';world?.setTalking(null)}
function failed(t){if(t!==voiceToken)return;clearTimeout(audioTimer);audio.pause();captionAt=elapsed+3;world?.setTalking(null);$('voiceRetry').hidden=muted||phase==='home'}
function line(key){const value=C.lines[key];if(!value)return;voiceKey=key;$('speaker').textContent=who(value[0]).name;$('message').innerHTML=textRuby(value[1]);world?.setTalking(null);captionAt=0;if(muted){captionAt=elapsed+Math.max(2.5,value[1].length*.08);return}if(paused)return;const t=++voiceToken;audio.src='language-audio/'+key+'.mp3';audioTimer=setTimeout(()=>failed(t),8000);audio.play().catch(()=>failed(t))}
function say(keys,kind='feedback'){stopVoice();purpose=kind;queue=Array.isArray(keys)?keys.slice():[keys];line(queue.shift())}
audio.addEventListener('playing',()=>{clearTimeout(audioTimer);$('voiceRetry').hidden=true;world?.setTalking(C.lines[voiceKey]?.[0])});
audio.addEventListener('waiting',()=>{const t=voiceToken;clearTimeout(audioTimer);audioTimer=setTimeout(()=>failed(t),8000)});audio.addEventListener('error',()=>failed(voiceToken));audio.addEventListener('ended',()=>{clearTimeout(audioTimer);world?.setTalking(null);if(queue.length)line(queue.shift());else purpose=''});
function tone(success){if(muted)return;try{const ac=window.kiteAudioContext||=new(window.AudioContext||window.webkitAudioContext)();ac.resume().catch(()=>{});const o=ac.createOscillator(),g=ac.createGain();o.frequency.value=success?780:470;g.gain.setValueAtTime(.045,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+.15);o.connect(g).connect(ac.destination);o.start();o.stop(ac.currentTime+.16)}catch{}}
function markWorld(spec){world.setRound(spec,index);Object.keys(buttons).forEach(id=>{buttons[id].hidden=!spec.cast.includes(id)||mode==='director';labels[id].hidden=!spec.cast.includes(id);labels[id].classList.toggle('speaking',id===spec.speaker);labels[id].classList.toggle('listening',id===spec.listener);labels[id].innerHTML=who(id).name+'<small>'+(id===spec.speaker?'正在说话':id===spec.listener?'正在听话':'在旁边')+'</small>';buttons[id].classList.remove('received')});$('context').textContent=who(spec.speaker).name+' → '+who(spec.listener).name+'：正在对话';$('wordBadge').innerHTML=ruby(spec.word);$('wordBadge').hidden=false}
function startRound(){mode='story';phase='play';roundDone=false;transitionAt=0;selected=null;document.body.classList.remove('director');$('directorTools').hidden=true;$('actions').hidden=false;$('startCard').hidden=true;draft=draft?.round===r().id&&!draft.complete?draft:entry();markWorld(r());$('place').textContent=r().place;$('progress').textContent=(index+1)+' / '+C.rounds.length+' · '+r().title;$('instruction').textContent='点伙伴，送风筝';say(r().intro,'rules');save()}
function choose(id){if(paused||phase!=='play'||mode!=='story'||!r().cast.includes(id))return;
if(purpose!=='rules')stopVoice();selected=id;const good=id===r().target;draft.attempts.push({person:id,correct:good,time:new Date().toISOString()});world.move(id,good);Object.keys(buttons).forEach(k=>buttons[k].classList.toggle('received',k===id));tone(good);save();
if(good){phase='success';roundDone=true;draft.complete=true;draft.withSupport=draft.hints>0||draft.attempts.length>1;records.push({...draft,time:new Date().toISOString()});records=records.slice(-80);save();$('instruction').textContent='送到啦！可以撤回换个想法';say(r().win,'win');transitionAt=elapsed+2.5}
else{$('instruction').textContent='送到了'+who(id).name+'，还可以换人';if(purpose!=='rules')say('retry')}
}
function undo(){if(paused||!started||mode!=='story'||!selected)return;stopVoice();if(roundDone){records=records.filter(x=>x.id!==draft.id);draft.complete=false;roundDone=false}transitionAt=0;phase='play';selected=null;draft.undo++;world.move(null);Object.values(buttons).forEach(b=>b.classList.remove('received'));$('instruction').textContent='风筝收回了，再选一个伙伴';say(r().request,'rules');save()}
function advance(){if(index<C.rounds.length-1){index++;draft=null;startRound()}else{phase='finish';transitionAt=0;$('finish').showModal();say('finish');save()}}
function setPaused(v){paused=v;world?.setPaused(v);if(v){audio.pause();clearTimeout(audioTimer);world?.setTalking(null)}else if(audio.getAttribute('src')&&!audio.ended&&!muted){const t=voiceToken;audioTimer=setTimeout(()=>failed(t),8000);audio.play().catch(()=>failed(t))}}
function openMenu(){setPaused(true);$('menu').showModal()}
function closeMenu(){ $('menu').close();setPaused(false)}
function rest(){['finish','menu','report'].forEach(id=>$(id).close());setPaused(true);stopVoice();$('restPanel').showModal()}
function report(){const prior=paused;setPaused(true);$('menu').close();$('finish').close();$('report').dataset.previous=prior?'paused':'active';$('reportBody').replaceChildren();const recent=records.slice(-12);if(!recent.length)$('reportBody').textContent='还没有完成记录，可以随时开始。';for(const item of recent){const article=document.createElement('article');if(item.kind==='director')article.textContent='自由编导：'+who(item.speaker)?.name+'对'+who(item.listener)?.name+'说“'+item.word+'”；风筝去了'+who(item.recipient)?.name+'。这是自主编排，不计对错。';else article.textContent=item.title+'｜带情境选用“'+item.word+'”：'+item.attempts.length+'次尝试，'+item.hints+'次线索，'+item.undo+'次撤回。'+(item.withSupport?'尝试或提示后完成。':'本轮无额外线索完成；不等同独立识字。');$('reportBody').appendChild(article)}$('report').showModal()}
function specDirector(){let {speaker,listener,word}=directorState;if(speaker===listener){listener=C.cast.find(c=>c.id!==speaker).id;directorState.listener=listener}$('chooseListener').value=listener;$('chooseSpeaker').value=speaker;const third=C.cast.find(c=>c.id!==speaker&&c.id!==listener).id;return {cast:[speaker,listener,third],speaker,listener,word}}
function updateDirector(){stopVoice();directorRun++;markWorld(specDirector());document.querySelectorAll('[data-word]').forEach(b=>b.classList.toggle('chosen',b.dataset.word===directorState.word));$('instruction').textContent='改角色、换字，再看看结果';$('speaker').textContent='珞伊的小剧场';$('message').innerHTML=who(directorState.speaker).name+'对'+who(directorState.listener).name+'说：<br>“风筝给'+ruby(directorState.word)+'。”'}
function director(){stopVoice();$('finish').close();setPaused(false);mode='director';phase='director';transitionAt=0;document.body.classList.add('director');$('directorTools').hidden=false;$('wordBadge').hidden=false;$('place').textContent='珞伊的小剧场';$('progress').textContent='自由编对话 · 原创拓展';updateDirector();say('director','rules')}
function launch(){if(paused||mode!=='director')return;const spec=specDirector(),recipient=spec.word==='我'?spec.speaker:spec.listener;world.move(recipient,true);say(spec.speaker+(spec.word==='我'?'Me':'You'));records.push({kind:'director',speaker:spec.speaker,listener:spec.listener,word:spec.word,recipient,time:new Date().toISOString()});records=records.slice(-80);$('instruction').textContent='风筝送给了'+who(recipient).name;save();tone(true)}
function fatal(){clearTimeout(window.langWatch);$('loading').hidden=true;$('fatal').hidden=false}
if(!C||!window.THREE||!window.createLanguageWorld){fatal();return}
for(const c of C.cast){const b=document.createElement('button');b.id='actor-'+c.id;b.className='target';b.setAttribute('aria-label','把风筝送给'+c.name);b.innerHTML='<span class="touch-dot">＋</span>';b.onclick=()=>choose(c.id);$('targets').appendChild(b);buttons[c.id]=b;const label=document.createElement('span');label.className='actor-name';$('names').appendChild(label);labels[c.id]=label;for(const id of['chooseSpeaker','chooseListener']){const option=document.createElement('option');option.value=c.id;option.textContent=c.name;$(id).appendChild(option)}}
try{world=createLanguageWorld({canvas:$('world'),stage:$('stage'),onFrame:items=>items.forEach(({id,point,foot})=>{const b=buttons[id];b.style.left=point.x+'px';b.style.top=point.y+'px';const label=labels[id];label.style.left=foot.x+'px';label.style.top=Math.max(foot.y,point.y+b.offsetHeight/2+3)+'px'})})}catch{fatal();return}
markWorld(r());$('wordBadge').hidden=true;Object.values(buttons).forEach(b=>b.hidden=true);$('loading').hidden=true;$('fatal').hidden=true;$('start').disabled=false;clearTimeout(window.langWatch);
if(validIndex&&index>0)$('start').textContent='继续放风筝';
$('start').onclick=()=>{started=true;startRound()};$('menuButton').onclick=openMenu;$('resume').onclick=closeMenu;$('rest').onclick=rest;$('finishRest').onclick=rest;$('back').onclick=()=>{$('restPanel').close();setPaused(false);if(phase==='finish')$('finish').showModal()};
$('undo').onclick=undo;$('hint').onclick=()=>{if(!started||phase!=='play')return;draft.hints++;save();say(r().hint,'hint')};$('replay').onclick=()=>{if(mode==='director'){say(directorState.speaker+(directorState.word==='我'?'Me':'You'));return}if(!started)return;draft.replays++;save();say(r().request,'rules')};$('voiceRetry').onclick=()=>{if(mode==='director')say('director','rules');else if(phase==='success')say(r().win,'win');else if(started)say(r().intro,'rules')};
$('sound').onclick=()=>{muted=!muted;stopVoice();$('sound').textContent=muted?'开启声音':'关闭声音';$('voiceRetry').hidden=true;save()};$('sound').textContent=muted?'开启声音':'关闭声音';
$('restart').onclick=()=>{$('menu').close();stopVoice();setPaused(false);index=0;draft=null;started=true;startRound()};$('reportButton').onclick=report;$('finishReport').onclick=report;$('closeReport').onclick=()=>{$('report').close();if(phase==='finish'){$('finish').showModal();setPaused(false)}else{$('menu').showModal()}};
$('director').onclick=director;$('chooseSpeaker').onchange=()=>{directorState.speaker=$('chooseSpeaker').value;updateDirector()};$('chooseListener').onchange=()=>{directorState.listener=$('chooseListener').value;updateDirector()};document.querySelectorAll('[data-word]').forEach(b=>b.onclick=()=>{directorState.word=b.dataset.word;updateDirector()});$('launch').onclick=launch;
$('download').onclick=()=>{const blob=new Blob([JSON.stringify({version:1,child:'珞伊',lesson:C.lesson,scope:'情境理解与带拼音认读，非独立识字测评',records,current:draft},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='珞伊-语文风筝探索记录.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),3000)};
document.querySelectorAll('dialog').forEach(d=>d.addEventListener('cancel',e=>e.preventDefault()));document.addEventListener('visibilitychange',()=>{if(document.hidden&&started&&!paused&&!document.querySelector('dialog[open]'))openMenu()});
function tick(t){requestAnimationFrame(tick);if(!paused)elapsed+=Math.min(.05,(t-last)/1000);last=t;if(!paused&&captionAt&&elapsed>=captionAt){captionAt=0;if(queue.length)line(queue.shift());else purpose=''}if(!paused&&phase==='success'&&transitionAt&&elapsed>=transitionAt&&!purpose&&audio.paused){transitionAt=0;advance()}}requestAnimationFrame(tick);
window.languageInspect=()=>({phase,index,round:r().id,mode,paused,elapsed,selected,world:world.inspect(),voice:{key:voiceKey,purpose,time:audio.currentTime,playing:!audio.paused,queue:queue.slice()},draft:JSON.parse(JSON.stringify(draft)),records:JSON.parse(JSON.stringify(records)),director:{...directorState},storageOK});
})();
